###Obter todos os elementos da sequência N = {n∈Z|1≤n < 10}

In [2]:
import numpy as np
n = np.arange(1,10,1)
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

###Obter todos os elementos do conjunto M = {m∈ Z|1 < m≤10}

In [3]:
m = np.arange(2,11,1)
m

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

###Obter todos os elementos da sequência de números ímpares entre 1 e 20. I = {2m − 1| m∈ Z , 1 < m≤20}

In [5]:
i = np.arange(1,20,2)
i

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

###Sequência de números racionais

###R = {rn ∈Q | − 2≤r n < 3 e n∈N}

no qual rn é definido por: r1 =− 2
r
n = r
n−1 + 0, 5

In [7]:
r = np.arange(-2,3,0.5)
r

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5])

###Criar uma sequência de números reais que se assemelha ao intervalo (− 2, 3]. Defina o passo em 0,1.

In [8]:
passo = 0.1
x = np.arange(-2+passo,3+passo, passo )
x

array([-1.90000000e+00, -1.80000000e+00, -1.70000000e+00, -1.60000000e+00,
       -1.50000000e+00, -1.40000000e+00, -1.30000000e+00, -1.20000000e+00,
       -1.10000000e+00, -1.00000000e+00, -9.00000000e-01, -8.00000000e-01,
       -7.00000000e-01, -6.00000000e-01, -5.00000000e-01, -4.00000000e-01,
       -3.00000000e-01, -2.00000000e-01, -1.00000000e-01,  1.77635684e-15,
        1.00000000e-01,  2.00000000e-01,  3.00000000e-01,  4.00000000e-01,
        5.00000000e-01,  6.00000000e-01,  7.00000000e-01,  8.00000000e-01,
        9.00000000e-01,  1.00000000e+00,  1.10000000e+00,  1.20000000e+00,
        1.30000000e+00,  1.40000000e+00,  1.50000000e+00,  1.60000000e+00,
        1.70000000e+00,  1.80000000e+00,  1.90000000e+00,  2.00000000e+00,
        2.10000000e+00,  2.20000000e+00,  2.30000000e+00,  2.40000000e+00,
        2.50000000e+00,  2.60000000e+00,  2.70000000e+00,  2.80000000e+00,
        2.90000000e+00,  3.00000000e+00])